aliyun:
  accessKeyID: 
  accessKeySecret: 
  regionID: cn-beijing
  fcEndpoint: https://id.cn-beijing-internal.fc.aliyuncs.com
  ossEndpoint: oss-cn-beijing-internal.aliyuncs.com
  userCodeBucket: jointfaas
  aliCodeBucket: alifaas
aws:
  accessKeyID: 
  accessKeySecret: 
  account: 
  lambdaRole: arn:aws-cn:iam::id:role/lambda-role
  regionID: cn-north-1
  userCodeBucket: jointfaas
  awsCodeBucket: awsfaas
openstack:
  storageRootDir: /tmp
server:
  port: 8080
storage:
  addr: localhost:50001
